src/Entity/Interfaces/Spell.php
<?php


namespace App\Entity\Interfaces;


interface Spell extends Entity
{

    public function getId(): ?int;
    public function getIdentifier(): ?string;
    public function getSchool(): ?SpellSchool;
    public function getLevel(): ?int;
    public function getCastingTime(): ?int;
    public function getIsRitual(): ?bool;
    public function getConcentration(): ?bool;
    public function getRangeDistance(): ?int;
    public function getVerbalComponent(): ?bool;
    public function getSomaticComponent(): ?bool;
    public function getMaterialComponents(): ?array;
    public function getNameEn(): ?string;
    public function getNameRu(): ?string;
    public function getDescriptionEn(): ?string;
    public function getDescriptionRu(): ?string;
    public function getCastingTimeType(): ?int;
    public function getCastingTimeDescriptionRu(): ?string;
    public function getCastingTimeDescriptionEn(): ?string;
    public function getDurationType(): ?int;
    public function getDuration(): ?int;
    public function getAreaType(): ?int;
    public function getAreaSize(): ?int;
    public function getRangeType(): ?int;

    public function getAreaSizeType(): ?int;

}

src/Entity/Spell.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use \App\Entity\Interfaces\Spell as SpellInterface;
/**
 * @ORM\Entity(repositoryClass="App\Repository\SpellRepository")
 */
class Spell implements SpellInterface
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255, nullable=false)
     */
    private $identifier;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\SpellSchool", inversedBy="spells")
     * @ORM\JoinColumn(nullable=false)
     */
    private $school;

    /**
     * @ORM\Column(type="integer")
     */
    private $level;

    /**
     * @ORM\Column(type="integer")
     */
    private $casting_time;

    /**
     * @ORM\Column(type="boolean", nullable=false)
     */
    private $is_ritual;

    /**
     * @ORM\Column(type="boolean", nullable=false)
     */
    private $concentration;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $range_distance;

    /**
     * @ORM\Column(type="boolean", nullable=false)
     */
    private $verbal_component;

    /**
     * @ORM\Column(type="boolean", nullable=false)
     */
    private $somatic_component;

    /**
     * @ORM\Column(type="simple_array", nullable=true)
     */
    private $material_components = [];

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\CharacterClass", inversedBy="spells")
     */
    private $characterClasses;

    /**
     * @ORM\Column(type="string", length=255, nullable=false)
     */
    private $nameEn;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $nameRu;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $descriptionEn;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $descriptionRu;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Source")
     */
    private $sources;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $casting_time_type;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $casting_time_description_ru;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $casting_time_description_en;

    /**
     * @ORM\Column(type="integer", nullable=false)
     */
    private $duration_type;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $duration;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $areaType;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $areaSize;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $rangeType;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $areaSizeType;

    public function __construct()
    {
        $this->characterClasses = new ArrayCollection();
        $this->sources = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getIdentifier(): ?string
    {
        return $this->identifier;
    }

    public function setIdentifier(string $identifier): self
    {
        $this->identifier = $identifier;

        return $this;
    }

    public function getSchool(): ?SpellSchool
    {
        return $this->school;
    }

    public function setSchool(?SpellSchool $school): self
    {
        $this->school = $school;

        return $this;
    }

    public function getLevel(): ?int
    {
        return $this->level;
    }

    public function setLevel(int $level): self
    {
        $this->level = $level;

        return $this;
    }

    public function getCastingTime(): ?int
    {
        return $this->casting_time;
    }

    public function setCastingTime(int $casting_time): self
    {
        $this->casting_time = $casting_time;

        return $this;
    }

    public function getIsRitual(): ?bool
    {
        return $this->is_ritual;
    }

    public function setIsRitual(bool $is_ritual): self
    {
        $this->is_ritual = $is_ritual;

        return $this;
    }

    public function getConcentration(): ?bool
    {
        return $this->concentration;
    }

    public function setConcentration(bool $concentration): self
    {
        $this->concentration = $concentration;

        return $this;
    }

    public function getRangeDistance(): ?int
    {
        return $this->range_distance;
    }

    public function setRangeDistance(?int $range_distance): self
    {
        $this->range_distance = $range_distance;

        return $this;
    }

    public function getVerbalComponent(): ?bool
    {
        return $this->verbal_component;
    }

    public function setVerbalComponent(bool $verbal_component): self
    {
        $this->verbal_component = $verbal_component;

        return $this;
    }

    public function getSomaticComponent(): ?bool
    {
        return $this->somatic_component;
    }

    public function setSomaticComponent(?bool $somatic_component): self
    {
        $this->somatic_component = $somatic_component;

        return $this;
    }

    public function getMaterialComponents(): ?array
    {
        return $this->material_components;
    }

    public function setMaterialComponents(?array $material_components): self
    {
        $this->material_components = $material_components;

        return $this;
    }

    /**
     * @return Collection|CharacterClass[]
     */
    public function getCharacterClasses(): Collection
    {
        return $this->characterClasses;
    }

    public function addCharacterClass(CharacterClass $characterClass): self
    {
        if (!$this->characterClasses->contains($characterClass)) {
            $this->characterClasses[] = $characterClass;
        }

        return $this;
    }

    public function removeCharacterClass(CharacterClass $characterClass): self
    {
        if ($this->characterClasses->contains($characterClass)) {
            $this->characterClasses->removeElement($characterClass);
        }

        return $this;
    }

    public function getNameEn(): ?string
    {
        return $this->nameEn;
    }

    public function setNameEn(string $nameEn): self
    {
        $this->nameEn = $nameEn;

        return $this;
    }

    public function getNameRu(): ?string
    {
        return $this->nameRu;
    }

    public function setNameRu(?string $nameRu): self
    {
        $this->nameRu = $nameRu;

        return $this;
    }

    public function getDescriptionEn(): ?string
    {
        return $this->descriptionEn;
    }

    public function setDescriptionEn(?string $descriptionEn): self
    {
        $this->descriptionEn = $descriptionEn;

        return $this;
    }

    public function getDescriptionRu(): ?string
    {
        return $this->descriptionRu;
    }

    public function setDescriptionRu(?string $descriptionRu): self
    {
        $this->descriptionRu = $descriptionRu;

        return $this;
    }

    /**
     * @return Collection|Source[]
     */
    public function getSources(): Collection
    {
        return $this->sources;
    }

    public function addSource(Source $source): self
    {
        if (!$this->sources->contains($source)) {
            $this->sources[] = $source;
        }

        return $this;
    }

    public function removeSource(Source $source): self
    {
        if ($this->sources->contains($source)) {
            $this->sources->removeElement($source);
        }

        return $this;
    }

    public function getCastingTimeType(): ?int
    {
        return $this->casting_time_type;
    }

    public function setCastingTimeType(int $casting_time_type): self
    {
        $this->casting_time_type = $casting_time_type;

        return $this;
    }

    public function getCastingTimeDescriptionRu(): ?string
    {
        return $this->casting_time_description_ru;
    }

    public function setCastingTimeDescriptionRu(?string $casting_time_description_ru): self
    {
        $this->casting_time_description_ru = $casting_time_description_ru;

        return $this;
    }

    public function getCastingTimeDescriptionEn(): ?string
    {
        return $this->casting_time_description_en;
    }

    public function setCastingTimeDescriptionEn(?string $casting_time_description_en): self
    {
        $this->casting_time_description_en = $casting_time_description_en;

        return $this;
    }

    public function getDurationType(): ?int
    {
        return $this->duration_type;
    }

    public function setDurationType(int $duration_type): self
    {
        $this->duration_type = $duration_type;

        return $this;
    }

    public function getDuration(): ?int
    {
        return $this->duration;
    }

    public function setDuration(?int $duration): self
    {
        $this->duration = $duration;

        return $this;
    }

    public function getAreaType(): ?int
    {
        return $this->areaType;
    }

    public function setAreaType(?int $areaType): self
    {
        $this->areaType = $areaType;

        return $this;
    }

    public function getAreaSize(): ?int
    {
        return $this->areaSize;
    }

    public function setAreaSize(?int $areaSize): self
    {
        $this->areaSize = $areaSize;

        return $this;
    }

    public function getRangeType(): ?int
    {
        return $this->rangeType;
    }

    public function setRangeType(int $rangeType): self
    {
        $this->rangeType = $rangeType;

        return $this;
    }

    public function getAreaSizeType(): ?int
    {
        return $this->areaSizeType;
    }

    public function setAreaSizeType(?int $areaSizeType): self
    {
        $this->areaSizeType = $areaSizeType;

        return $this;
    }
}

src/Form/SpellType.php
<?php

namespace App\Form;

use App\Entity\Spell;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class SpellType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name')
            ->add('level')
            ->add('casting_time')
            ->add('is_ritual')
            ->add('concentration')
            ->add('range_distance')
            ->add('verbal_component')
            ->add('somatic_component')
            ->add('material_components')
            ->add('school')
            ->add('source')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Spell::class,
        ]);
    }
}

src/Controller/SpellController.php
<?php

namespace App\Controller;

use App\Entity\Spell;
use App\Form\Spell4Type;
use App\Repository\SpellRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/spell")
 */
class SpellController extends AbstractController
{
    /**
     * @Route("/", name="spell_index", methods={"GET"})
     */
    public function index(SpellRepository $spellRepository): Response
    {
        return $this->render('spell/index.html.twig', ['spells' => $spellRepository->findAll()]);
    }

    /**
     * @Route("/new", name="spell_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $spell = new Spell();
        $form = $this->createForm(Spell4Type::class, $spell);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($spell);
            $entityManager->flush();

            return $this->redirectToRoute('spell_index');
        }

        return $this->render('spell/new.html.twig', [
            'spell' => $spell,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="spell_show", methods={"GET"})
     */
    public function show(Spell $spell): Response
    {
        return $this->render('spell/show.html.twig', ['spell' => $spell]);
    }

    /**
     * @Route("/{id}/edit", name="spell_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Spell $spell): Response
    {
        $form = $this->createForm(Spell4Type::class, $spell);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('spell_index', ['id' => $spell->getId()]);
        }

        return $this->render('spell/edit.html.twig', [
            'spell' => $spell,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="spell_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Spell $spell): Response
    {
        if ($this->isCsrfTokenValid('delete'.$spell->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($spell);
            $entityManager->flush();
        }

        return $this->redirectToRoute('spell_index');
    }
}

templates/spell/_delete_form.html.twig
<form method="post" action="{{ path('spell_delete', {'id': spell.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ spell.id) }}">
    <button class="btn">Delete</button>
</form>

templates/spell/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/spell/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Spell{% endblock %}

{% block body %}
    <h1>Edit Spell</h1>

    {{ include('spell/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('spell_index') }}">back to list</a>

    {{ include('spell/_delete_form.html.twig') }}
{% endblock %}

templates/spell/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Spell index{% endblock %}

{% block body %}
    <h1>Spell index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Identifier</th>
                <th>Level</th>
                <th>Casting_time</th>
                <th>Is_ritual</th>
                <th>Concentration</th>
                <th>Range_distance</th>
                <th>Verbal_component</th>
                <th>Somatic_component</th>
                <th>Material_components</th>
                <th>NameEn</th>
                <th>NameRu</th>
                <th>DescriptionEn</th>
                <th>DescriptionRu</th>
                <th>Casting_time_type</th>
                <th>Casting_time_description_ru</th>
                <th>Casting_time_description_en</th>
                <th>Duration_type</th>
                <th>Duration</th>
                <th>AreaType</th>
                <th>AreaSize</th>
                <th>RangeType</th>
                <th>sources</th>
                <th>AreaSizeType</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for spell in spells %}
            <tr>
                <td>{{ spell.id }}</td>
                <td>{{ spell.identifier }}</td>
                <td>{{ spell.level }}</td>
                <td>{{ spell.castingTime }}</td>
                <td>{{ spell.isRitual ? 'Yes' : 'No' }}</td>
                <td>{{ spell.concentration ? 'Yes' : 'No' }}</td>
                <td>{{ spell.rangeDistance }}</td>
                <td>{{ spell.verbalComponent ? 'Yes' : 'No' }}</td>
                <td>{{ spell.somaticComponent ? 'Yes' : 'No' }}</td>
                <td>{{ spell.materialComponents|join(',') }}</td>
                <td>{{ spell.nameEn }}</td>
                <td>{{ spell.nameRu }}</td>
                <td>{{ spell.descriptionEn }}</td>
                <td>{{ spell.descriptionRu }}</td>
                <td>{{ spell.castingTimeType }}</td>
                <td>{{ spell.castingTimeDescriptionRu }}</td>
                <td>{{ spell.castingTimeDescriptionEn }}</td>
                <td>{{ spell.durationType }}</td>
                <td>{{ spell.duration }}</td>
                <td>{{ spell.areaType }}</td>
                <td>{{ spell.areaSize }}</td>
                <td>{{ spell.rangeType }}</td>
                <td>{{ spell.sources|join(',') }}</td>
                <td>{{ spell.areaSizeType }}</td>
                <td>
                    <a href="{{ path('spell_show', {'id': spell.id}) }}">show</a>
                    <a href="{{ path('spell_edit', {'id': spell.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="24">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('spell_new') }}">Create new</a>
{% endblock %}

templates/spell/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Spell{% endblock %}

{% block body %}
    <h1>Create new Spell</h1>

    {{ include('spell/_form.html.twig') }}

    <a href="{{ path('spell_index') }}">back to list</a>
{% endblock %}

templates/spell/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Spell{% endblock %}

{% block body %}
    <h1>Spell</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ spell.id }}</td>
            </tr>
            <tr>
                <th>Identifier</th>
                <td>{{ spell.identifier }}</td>
            </tr>
            <tr>
                <th>Level</th>
                <td>{{ spell.level }}</td>
            </tr>
            <tr>
                <th>Casting_time</th>
                <td>{{ spell.castingTime }}</td>
            </tr>
            <tr>
                <th>Is_ritual</th>
                <td>{{ spell.isRitual ? 'Yes' : 'No' }}</td>
            </tr>
            <tr>
                <th>Concentration</th>
                <td>{{ spell.concentration ? 'Yes' : 'No' }}</td>
            </tr>
            <tr>
                <th>Range_distance</th>
                <td>{{ spell.rangeDistance }}</td>
            </tr>
            <tr>
                <th>Verbal_component</th>
                <td>{{ spell.verbalComponent ? 'Yes' : 'No' }}</td>
            </tr>
            <tr>
                <th>Somatic_component</th>
                <td>{{ spell.somaticComponent ? 'Yes' : 'No' }}</td>
            </tr>
            <tr>
                <th>Material_components</th>
                <td>{{ spell.materialComponents }}</td>
            </tr>
            <tr>
                <th>NameEn</th>
                <td>{{ spell.nameEn }}</td>
            </tr>
            <tr>
                <th>NameRu</th>
                <td>{{ spell.nameRu }}</td>
            </tr>
            <tr>
                <th>DescriptionEn</th>
                <td>{{ spell.descriptionEn }}</td>
            </tr>
            <tr>
                <th>DescriptionRu</th>
                <td>{{ spell.descriptionRu }}</td>
            </tr>
            <tr>
                <th>Casting_time_type</th>
                <td>{{ spell.castingTimeType }}</td>
            </tr>
            <tr>
                <th>Casting_time_description_ru</th>
                <td>{{ spell.castingTimeDescriptionRu }}</td>
            </tr>
            <tr>
                <th>Casting_time_description_en</th>
                <td>{{ spell.castingTimeDescriptionEn }}</td>
            </tr>
            <tr>
                <th>Duration_type</th>
                <td>{{ spell.durationType }}</td>
            </tr>
            <tr>
                <th>Duration</th>
                <td>{{ spell.duration }}</td>
            </tr>
            <tr>
                <th>AreaType</th>
                <td>{{ spell.areaType }}</td>
            </tr>
            <tr>
                <th>AreaSize</th>
                <td>{{ spell.areaSize }}</td>
            </tr>
            <tr>
                <th>RangeType</th>
                <td>{{ spell.rangeType }}</td>
            </tr>
            <tr>
                <th>AreaSizeType</th>
                <td>{{ spell.areaSizeType }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('spell_index') }}">back to list</a>

    <a href="{{ path('spell_edit', {'id': spell.id}) }}">edit</a>

    {{ include('spell/_delete_form.html.twig') }}
{% endblock %}